/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas;
import conexion.*;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALEX JAVIER
 */
public class empleadosCedula extends javax.swing.JFrame {
  private DefaultTableModel model;

    /**
     * Creates new form discapaciddes
     */
    public empleadosCedula() {
        initComponents();
        cargarTabla("");
        
    }

    void cargarTabla(String cedula){
        
        
        conexion cc = new conexion();
        Connection cn = cc.conectar("");
        
        String titulos []= {"Cedula","Nombre","Apellidos","EstadoCivil","Genero","Direccion","Ubicacion Fisica","Foto","Telefono","Celular"};
        
        model= new DefaultTableModel(null,titulos);
        String registro[] = new String [11]; 
        String sql="";
        sql = "Select Num_Ced, Nom_Em_1, Nom_Em_2, Ape_Em_1, Ape_Em_2, ESTADO_CI_EM, GENERO, DIR_EM, UBI_FIS, FOTO, TEL_EM, CEL_EM, FEC_ING_EM_EM from Empleados "
                + "WHERE Num_Ced like '"+cedula+"%'";
        try{
        Statement psd = cn.createStatement();
        ResultSet rs = psd.executeQuery(sql);
        while(rs.next()){
            // , , , , , , , 
            registro[0]=rs.getString("Num_Ced");
            registro[1]=rs.getString("Nom_Em_1")+" "+rs.getString("Nom_Em_2");
            registro[2]=rs.getString("Ape_Em_1")+" "+rs.getString("Ape_Em_2");
            registro[3]=rs.getString("ESTADO_CI_EM");
            registro[4]=rs.getString("GENERO");
             registro[5]=rs.getString("DIR_EM");
              registro[6]=rs.getString("UBI_FIS");
            registro[7]=rs.getString("FOTO");
            registro[8]=rs.getString("TEL_EM");
            registro[9]=rs.getString("CEL_EM");
            registro[10]=rs.getString("FEC_ING_EM_EM");
            model.addRow(registro);
        }
          tblDiscapacidades.setModel(model);
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);
        }
    }    
    
     void cargarTablaNombre(String nombre){
        
        
        conexion cc = new conexion();
        Connection cn = cc.conectar("");
        
        String titulos []= {"Cedula","Nombre","Apellidos","EstadoCivil","Genero","Direccion","Ubicacion Fisica","Foto","Telefono","Celular"};
        
        model= new DefaultTableModel(null,titulos);
        String registro[] = new String [11]; 
        String sql="";
        sql = "Select Num_Ced, Nom_Em_1, Nom_Em_2, Ape_Em_1, Ape_Em_2, ESTADO_CI_EM, GENERO, DIR_EM, UBI_FIS, FOTO, TEL_EM, CEL_EM, FEC_ING_EM_EM from Empleados "
                + "WHERE Nom_Em_1 like '"+nombre+"%'";
        try{
        Statement psd = cn.createStatement();
        ResultSet rs = psd.executeQuery(sql);
        while(rs.next()){
            // , , , , , , , 
            registro[0]=rs.getString("Num_Ced");
            registro[1]=rs.getString("Nom_Em_1")+" "+rs.getString("Nom_Em_2");
            registro[2]=rs.getString("Ape_Em_1")+" "+rs.getString("Ape_Em_2");
            registro[3]=rs.getString("ESTADO_CI_EM");
            registro[4]=rs.getString("GENERO");
             registro[5]=rs.getString("DIR_EM");
              registro[6]=rs.getString("UBI_FIS");
            registro[7]=rs.getString("FOTO");
            registro[8]=rs.getString("TEL_EM");
            registro[9]=rs.getString("CEL_EM");
            registro[10]=rs.getString("FEC_ING_EM_EM");
            model.addRow(registro);
        }
          tblDiscapacidades.setModel(model);
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);
        }
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiscapacidades = new javax.swing.JTable();
        txtCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Empleados");

        jLabel2.setText("Numero de Cedula");

        tblDiscapacidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDiscapacidades);

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        jLabel3.setText("Nombre");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(9, 9, 9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(txtCedula)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        //cargarTabla(txtCedula.getText());
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
         cargarTablaNombre(txtNombre.getText());
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyPressed
        // TODO add your handling code here:
       
         cargarTabla(txtCedula.getText());
    }//GEN-LAST:event_txtCedulaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empleadosCedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empleadosCedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empleadosCedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empleadosCedula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empleadosCedula().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDiscapacidades;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
